#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 13 19:08:59 2023

@author: shubhamjuneja
"""

import turtle
t= turtle.Turtle()
s = turtle.Screen()
s.bgcolor('black')
t.speed(0.5)

col= ('yellow','red','pink','cyan','light green','blue')

for i in range(100):
    t.pencolor(col[i%6])
    t.circle(190-i/2,90)
    t.lt(90)
    t.circle(190-i/3,90)
    t.lt(60)
    
s.exitonclick()