#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 17 20:55:38 2023

@author: shubhamjuneja
"""

import turtle
t = turtle.Turtle()

i = 0
t.speed(0)
t.hideturtle()
for i in range(100):
    t.circle(20)
    t.right(90)
    t.forward(20)
    #hands
    if i%2==0:
        t.left(30)
        t.forward(50)
        t.left(180)
        t.forward(50)
        t.right(30)
        t.left(180)
    else:
        t.right(30)
        t.forward(50)
        t.left(180)
        t.forward(50)
        t.left(30)
        t.left(180)
    
    
        
    t.forward(80)
    
    if i%2==0:
        t.right(30)
        t.forward(50)
        t.left(180)
        t.forward(50)
        t.left(30)
        t.left(180)
    else:
        t.left(30)
        t.forward(50)
        t.left(180)
        t.forward(50)
        t.right(30)
        t.left(180)
    
    t.forward(40)
    
    t.penup()
    t.goto(i*10,0)
    t.left(90)
    t.pendown()
    t.clear()
    
    
